version: '3.8'

services:
  mysql_container:
    image: mysql:8
    container_name: mysql_container
    ports:
      - "3307:3306" # Host 3307 → Container 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qap2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot_container:
    build: .
    container_name: springboot_container
    ports:
      - "8080:8080"
    depends_on:
      mysql_container:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/qap2
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - .:/app
    restart: on-failure

volumes:
  mysql_data:
